### ISSUE TITLE
Empty planets

### ISSUE THREAD

**Issue by ussjohnson** [mpigsley/sectors-without-number#237]
Would it be possible to add randomly generated and/or user inputted empty planets within systems? As it stands, every planet/asteroid belt has to be a point of interest with tags and a population or abandoned colony. It would be nice to be able to add empty planets like Mercury to systems: no population, just there for depth and scenery.

**Comment by mpigsley** [comment]
@ussjohnson You can add a planet to a system and remove all the tags, populatation, etc. etc. If you add the planet from a system, you can uncheck the random generation so that it creates _only_ a blank planet. See attached image:

<img width="453" alt="Screen Shot 2019-11-18 at 1 45 14 PM" src="https://user-images.githubusercontent.com/3017491/69084448-e28b8800-0a09-11ea-8d93-77e2a3af901f.png">

**Comment by ussjohnson** [comment]
That's good to know! Thanks for showing me how to do that!
