### ISSUE TITLE
Add features from Suns of Gold

### ISSUE THREAD

**Issue by ThePiachu** [mpigsley/sectors-without-number#74]
The Suns of Gold expansion added a trade layer to each planet, might be useful to incorporate those features into the sector generator.

**Comment by mpigsley** [comment]
Sadly, I can't do that since Suns of Gold is a paid product. I'm hoping to cover this use case by adding in custom [attributes](https://github.com/mpigsley/sectors-without-number/issues/66) and [world tags](https://github.com/mpigsley/sectors-without-number/issues/65). Any other Suns of Gold features you'd like to see that those two issues don't cover?

**Comment by ThePiachu** [comment]
I guess if you represented things like "-2 Agricultural, -1 Livestock, +1 Biotech, +2 Tool" as Attributes, and have the trade good / trouble tables as part of world tags, that might be enough. Those two would have to be generated together though, so an "Agricultural Worlds" tag would produce certain attributes.

Similarly, you would want a pool of separate tags for Trade Tag Elements that you would generate one of for each world. So I suppose you would need to specify pools of tags and ensure there is one tag from each pool on each world?

**Comment by mpigsley** [comment]
That's great info. I'll keep this in mind when I go to create those custom categories.
